config/routes.rb
Rails.application.routes.draw do
  root :to => "contacts#index"
  resources :events
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :email, :message, :user, presence: true
	validates :email, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
	validates :event_date, :resource, :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact_events = Event.where(user: @contact.user).paginate(:page => params[:page], :per_page => 5).order(:created_at)
  end

  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        format.json { render :show, status: :created, location: @contact }
      else
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:email, :message, :user)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.json { render :show, status: :created, location: @event }
      else
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_date, :resource, :user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Email</th>
        <th>Message</th>
        <th>See Events...</th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.email %></td>
          <td><%= contact.message %></td>
          <td><%= link_to 'Show', contact %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @contact %>

app/views/contacts/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<h3>Eventos</h3>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Resource</th>
        <th>Date</th>
      </tr>
    </thead>

    <tbody>
      <% @contact_events.each do |e| %>
        <tr>
          <td><%= e.resource.split("/").last %></td>
          <td><%= e.event_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @contact_events %>
<br>
<br>
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UamingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills float-xs-right">
            <li class="nav-item">
              <a class="nav-link" href="#" onclick="alert('Click it better!!!!')">Click Here</a>
            </li>
          </ul>
        </nav>
        <h3 class="text-muted">UAMing The Application</h3>
      </div>
      <%= yield %>
      <footer class="footer">
        <p>&copy; Uaming Application 2016</p>
      </footer>
    </div>
    
  </body>
</html>